"""empty message

Revision ID: 0a9b8481363e
Revises: a9cb843097a3
Create Date: 2023-11-27 15:53:46.181168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9b8481363e'
down_revision: Union[str, None] = 'a9cb843097a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
