"""empty message

Revision ID: 31209af92e06
Revises: 71145dabdcb7
Create Date: 2023-11-29 11:47:58.373772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31209af92e06'
down_revision: Union[str, None] = '71145dabdcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('trs_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_table.id'], name='association_table_deal_id_fkey'),
    sa.ForeignKeyConstraint(['trs_id'], ['transaction.id'], name='association_table_trs_id_fkey')
    )
    # ### end Alembic commands ###
