"""empty message

Revision ID: 448cf10b78f3
Revises: 
Create Date: 2023-11-28 17:55:37.736272

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '448cf10b78f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('buy_deals_amount', sa.Float(), nullable=False),
                    sa.Column('sell_deals_amount', sa.Float(), nullable=False),
                    sa.Column('cash', sa.Float(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('commodity',
                    sa.Column('ticker', sa.String(length=16), nullable=False),
                    sa.Column('description', sa.String(length=2048), nullable=False),
                    sa.Column('specification', sa.String(length=2048), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ticker')
                    )
    op.create_table('deal_table',
                    sa.Column('account', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(length=32), nullable=False),
                    sa.Column('status', sa.String(length=16), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('deal_transaction_table',
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('direction', sa.String(length=8), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order',
                    sa.Column('account', sa.String(length=64), nullable=False),
                    sa.Column('ticker', sa.String(length=32), nullable=False),
                    sa.Column('status', sa.String(length=16), nullable=False),
                    sa.Column('dtype', sa.String(length=16), nullable=False),
                    sa.Column('direction', sa.String(length=8), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transaction',
                    sa.Column('ticker', sa.String(length=16), nullable=False),
                    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('buyer', sa.String(length=64), nullable=False),
                    sa.Column('seller', sa.String(length=64), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('order')
    op.drop_table('deal_transaction_table')
    op.drop_table('deal_table')
    op.drop_table('commodity')
    op.drop_table('account')
    # ### end Alembic commands ###
