"""empty message

Revision ID: 44fbe841792d
Revises: 2414c0a2311c
Create Date: 2023-11-28 17:37:36.225198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44fbe841792d'
down_revision: Union[str, None] = '2414c0a2311c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_table',
                    sa.Column('account', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(length=32), nullable=False),
                    sa.Column('status', sa.String(length=16), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('deal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
                    sa.Column('ticker', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
                    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.Column('account', sa.UUID(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='deal_pkey')
                    )
    op.drop_table('deal_table')
    # ### end Alembic commands ###
