"""empty message

Revision ID: 764086a96ba5
Revises: 0a9b8481363e
Create Date: 2023-11-28 15:41:41.428417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '764086a96ba5'
down_revision: Union[str, None] = '0a9b8481363e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_transaction',
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('deal', 'transaction')
    op.drop_column('deal', 'documents')
    op.drop_column('deal', 'account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('account', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('deal', sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('transaction', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_table('deal_transaction')
    # ### end Alembic commands ###
