"""empty message

Revision ID: b6b0f3118278
Revises: 764086a96ba5
Create Date: 2023-11-28 15:42:10.679370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b0f3118278'
down_revision: Union[str, None] = '764086a96ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('account', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'account')
    # ### end Alembic commands ###
