"""empty message

Revision ID: c7507aa6166a
Revises: b9d70d92c42e
Create Date: 2023-11-15 12:55:14.937072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7507aa6166a'
down_revision: Union[str, None] = 'b9d70d92c42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('transaction', sa.String(length=64), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal')
    # ### end Alembic commands ###
