"""empty message

Revision ID: caf9646b2ca8
Revises: 448cf10b78f3
Create Date: 2023-11-28 18:06:04.216793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf9646b2ca8'
down_revision: Union[str, None] = '448cf10b78f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_transaction_table', sa.Column('deal_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'deal_transaction_table', 'deal_table', ['deal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal_transaction_table', type_='foreignkey')
    op.drop_column('deal_transaction_table', 'deal_id')
    # ### end Alembic commands ###
