"""empty message

Revision ID: dc6166b85ae0
Revises: f861e99f5966
Create Date: 2023-11-30 11:44:09.685838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6166b85ae0'
down_revision: Union[str, None] = 'f861e99f5966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('buyer', sa.UUID(), nullable=False))
    op.add_column('transaction', sa.Column('seller', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'seller')
    op.drop_column('transaction', 'buyer')
    # ### end Alembic commands ###
