"""empty message

Revision ID: f861e99f5966
Revises: 31209af92e06
Create Date: 2023-11-30 11:41:58.867584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f861e99f5966'
down_revision: Union[str, None] = '31209af92e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'seller')
    op.drop_column('transaction', 'buyer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('buyer', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('seller', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
